package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcAirToAirHeatRecoveryTypeEnum = ENUMERATION OF
 * (FIXEDPLATECOUNTERFLOWEXCHANGER
 * ,FIXEDPLATECROSSFLOWEXCHANGER
 * ,FIXEDPLATEPARALLELFLOWEXCHANGER
 * ,ROTARYWHEEL
 * ,RUNAROUNDCOILLOOP
 * ,HEATPIPE
 * ,TWINTOWERENTHALPYRECOVERYLOOPS
 * ,THERMOSIPHONSEALEDTUBEHEATEXCHANGERS
 * ,THERMOSIPHONCOILTYPEHEATEXCHANGERS
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcairtoairheatrecoverytypeenum.htm">IfcAirToAirHeatRecoveryTypeEnum</a>
 */
public enum IfcAirToAirHeatRecoveryTypeEnum {FIXEDPLATECOUNTERFLOWEXCHANGER,FIXEDPLATECROSSFLOWEXCHANGER,FIXEDPLATEPARALLELFLOWEXCHANGER,ROTARYWHEEL,RUNAROUNDCOILLOOP,HEATPIPE,TWINTOWERENTHALPYRECOVERYLOOPS,THERMOSIPHONSEALEDTUBEHEATEXCHANGERS,THERMOSIPHONCOILTYPEHEATEXCHANGERS,USERDEFINED,NOTDEFINED}