package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcDistributionSystemEnum = ENUMERATION OF
 * (AIRCONDITIONING
 * ,AUDIOVISUAL
 * ,CHEMICAL
 * ,CHILLEDWATER
 * ,COMMUNICATION
 * ,COMPRESSEDAIR
 * ,CONDENSERWATER
 * ,CONTROL
 * ,CONVEYING
 * ,DATA
 * ,DISPOSAL
 * ,DOMESTICCOLDWATER
 * ,DOMESTICHOTWATER
 * ,DRAINAGE
 * ,EARTHING
 * ,ELECTRICAL
 * ,ELECTROACOUSTIC
 * ,EXHAUST
 * ,FIREPROTECTION
 * ,FUEL
 * ,GAS
 * ,HAZARDOUS
 * ,HEATING
 * ,LIGHTING
 * ,LIGHTNINGPROTECTION
 * ,MUNICIPALSOLIDWASTE
 * ,OIL
 * ,OPERATIONAL
 * ,POWERGENERATION
 * ,RAINWATER
 * ,REFRIGERATION
 * ,SECURITY
 * ,SEWAGE
 * ,SIGNAL
 * ,STORMWATER
 * ,TELEPHONE
 * ,TV
 * ,VACUUM
 * ,VENT
 * ,VENTILATION
 * ,WASTEWATER
 * ,WATERSUPPLY
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcdistributionsystemenum.htm">IfcDistributionSystemEnum</a>
 */
public enum IfcDistributionSystemEnum {AIRCONDITIONING,AUDIOVISUAL,CHEMICAL,CHILLEDWATER,COMMUNICATION,COMPRESSEDAIR,CONDENSERWATER,CONTROL,CONVEYING,DATA,DISPOSAL,DOMESTICCOLDWATER,DOMESTICHOTWATER,DRAINAGE,EARTHING,ELECTRICAL,ELECTROACOUSTIC,EXHAUST,FIREPROTECTION,FUEL,GAS,HAZARDOUS,HEATING,LIGHTING,LIGHTNINGPROTECTION,MUNICIPALSOLIDWASTE,OIL,OPERATIONAL,POWERGENERATION,RAINWATER,REFRIGERATION,SECURITY,SEWAGE,SIGNAL,STORMWATER,TELEPHONE,TV,VACUUM,VENT,VENTILATION,WASTEWATER,WATERSUPPLY,USERDEFINED,NOTDEFINED}