package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcDerivedUnitEnum = ENUMERATION OF
 * (ANGULARVELOCITYUNIT
 * ,AREADENSITYUNIT
 * ,COMPOUNDPLANEANGLEUNIT
 * ,DYNAMICVISCOSITYUNIT
 * ,HEATFLUXDENSITYUNIT
 * ,INTEGERCOUNTRATEUNIT
 * ,ISOTHERMALMOISTURECAPACITYUNIT
 * ,KINEMATICVISCOSITYUNIT
 * ,LINEARVELOCITYUNIT
 * ,MASSDENSITYUNIT
 * ,MASSFLOWRATEUNIT
 * ,MOISTUREDIFFUSIVITYUNIT
 * ,MOLECULARWEIGHTUNIT
 * ,SPECIFICHEATCAPACITYUNIT
 * ,THERMALADMITTANCEUNIT
 * ,THERMALCONDUCTANCEUNIT
 * ,THERMALRESISTANCEUNIT
 * ,THERMALTRANSMITTANCEUNIT
 * ,VAPORPERMEABILITYUNIT
 * ,VOLUMETRICFLOWRATEUNIT
 * ,ROTATIONALFREQUENCYUNIT
 * ,TORQUEUNIT
 * ,MOMENTOFINERTIAUNIT
 * ,LINEARMOMENTUNIT
 * ,LINEARFORCEUNIT
 * ,PLANARFORCEUNIT
 * ,MODULUSOFELASTICITYUNIT
 * ,SHEARMODULUSUNIT
 * ,LINEARSTIFFNESSUNIT
 * ,ROTATIONALSTIFFNESSUNIT
 * ,MODULUSOFSUBGRADEREACTIONUNIT
 * ,ACCELERATIONUNIT
 * ,CURVATUREUNIT
 * ,HEATINGVALUEUNIT
 * ,IONCONCENTRATIONUNIT
 * ,LUMINOUSINTENSITYDISTRIBUTIONUNIT
 * ,MASSPERLENGTHUNIT
 * ,MODULUSOFLINEARSUBGRADEREACTIONUNIT
 * ,MODULUSOFROTATIONALSUBGRADEREACTIONUNIT
 * ,PHUNIT
 * ,ROTATIONALMASSUNIT
 * ,SECTIONAREAINTEGRALUNIT
 * ,SECTIONMODULUSUNIT
 * ,SOUNDPOWERLEVELUNIT
 * ,SOUNDPOWERUNIT
 * ,SOUNDPRESSURELEVELUNIT
 * ,SOUNDPRESSUREUNIT
 * ,TEMPERATUREGRADIENTUNIT
 * ,TEMPERATURERATEOFCHANGEUNIT
 * ,THERMALEXPANSIONCOEFFICIENTUNIT
 * ,WARPINGCONSTANTUNIT
 * ,WARPINGMOMENTUNIT
 * ,USERDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcderivedunitenum.htm">IfcDerivedUnitEnum</a>
 */
public enum IfcDerivedUnitEnum {ANGULARVELOCITYUNIT,AREADENSITYUNIT,COMPOUNDPLANEANGLEUNIT,DYNAMICVISCOSITYUNIT,HEATFLUXDENSITYUNIT,INTEGERCOUNTRATEUNIT,ISOTHERMALMOISTURECAPACITYUNIT,KINEMATICVISCOSITYUNIT,LINEARVELOCITYUNIT,MASSDENSITYUNIT,MASSFLOWRATEUNIT,MOISTUREDIFFUSIVITYUNIT,MOLECULARWEIGHTUNIT,SPECIFICHEATCAPACITYUNIT,THERMALADMITTANCEUNIT,THERMALCONDUCTANCEUNIT,THERMALRESISTANCEUNIT,THERMALTRANSMITTANCEUNIT,VAPORPERMEABILITYUNIT,VOLUMETRICFLOWRATEUNIT,ROTATIONALFREQUENCYUNIT,TORQUEUNIT,MOMENTOFINERTIAUNIT,LINEARMOMENTUNIT,LINEARFORCEUNIT,PLANARFORCEUNIT,MODULUSOFELASTICITYUNIT,SHEARMODULUSUNIT,LINEARSTIFFNESSUNIT,ROTATIONALSTIFFNESSUNIT,MODULUSOFSUBGRADEREACTIONUNIT,ACCELERATIONUNIT,CURVATUREUNIT,HEATINGVALUEUNIT,IONCONCENTRATIONUNIT,LUMINOUSINTENSITYDISTRIBUTIONUNIT,MASSPERLENGTHUNIT,MODULUSOFLINEARSUBGRADEREACTIONUNIT,MODULUSOFROTATIONALSUBGRADEREACTIONUNIT,PHUNIT,ROTATIONALMASSUNIT,SECTIONAREAINTEGRALUNIT,SECTIONMODULUSUNIT,SOUNDPOWERLEVELUNIT,SOUNDPOWERUNIT,SOUNDPRESSURELEVELUNIT,SOUNDPRESSUREUNIT,TEMPERATUREGRADIENTUNIT,TEMPERATURERATEOFCHANGEUNIT,THERMALEXPANSIONCOEFFICIENTUNIT,WARPINGCONSTANTUNIT,WARPINGMOMENTUNIT,USERDEFINED}