package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcDoorTypeOperationEnum = ENUMERATION OF
 * (SINGLE_SWING_LEFT
 * ,SINGLE_SWING_RIGHT
 * ,DOUBLE_DOOR_SINGLE_SWING
 * ,DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_LEFT
 * ,DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_RIGHT
 * ,DOUBLE_SWING_LEFT
 * ,DOUBLE_SWING_RIGHT
 * ,DOUBLE_DOOR_DOUBLE_SWING
 * ,SLIDING_TO_LEFT
 * ,SLIDING_TO_RIGHT
 * ,DOUBLE_DOOR_SLIDING
 * ,FOLDING_TO_LEFT
 * ,FOLDING_TO_RIGHT
 * ,DOUBLE_DOOR_FOLDING
 * ,REVOLVING
 * ,ROLLINGUP
 * ,SWING_FIXED_LEFT
 * ,SWING_FIXED_RIGHT
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcdoortypeoperationenum.htm">IfcDoorTypeOperationEnum</a>
 */
public enum IfcDoorTypeOperationEnum {SINGLE_SWING_LEFT,SINGLE_SWING_RIGHT,DOUBLE_DOOR_SINGLE_SWING,DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_LEFT,DOUBLE_DOOR_SINGLE_SWING_OPPOSITE_RIGHT,DOUBLE_SWING_LEFT,DOUBLE_SWING_RIGHT,DOUBLE_DOOR_DOUBLE_SWING,SLIDING_TO_LEFT,SLIDING_TO_RIGHT,DOUBLE_DOOR_SLIDING,FOLDING_TO_LEFT,FOLDING_TO_RIGHT,DOUBLE_DOOR_FOLDING,REVOLVING,ROLLINGUP,SWING_FIXED_LEFT,SWING_FIXED_RIGHT,USERDEFINED,NOTDEFINED}