package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcElectricApplianceTypeEnum = ENUMERATION OF
 * (DISHWASHER
 * ,ELECTRICCOOKER
 * ,FREESTANDINGELECTRICHEATER
 * ,FREESTANDINGFAN
 * ,FREESTANDINGWATERHEATER
 * ,FREESTANDINGWATERCOOLER
 * ,FREEZER
 * ,FRIDGE_FREEZER
 * ,HANDDRYER
 * ,KITCHENMACHINE
 * ,MICROWAVE
 * ,PHOTOCOPIER
 * ,REFRIGERATOR
 * ,TUMBLEDRYER
 * ,VENDINGMACHINE
 * ,WASHINGMACHINE
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcelectricappliancetypeenum.htm">IfcElectricApplianceTypeEnum</a>
 */
public enum IfcElectricApplianceTypeEnum {DISHWASHER,ELECTRICCOOKER,FREESTANDINGELECTRICHEATER,FREESTANDINGFAN,FREESTANDINGWATERHEATER,FREESTANDINGWATERCOOLER,FREEZER,FRIDGE_FREEZER,HANDDRYER,KITCHENMACHINE,MICROWAVE,PHOTOCOPIER,REFRIGERATOR,TUMBLEDRYER,VENDINGMACHINE,WASHINGMACHINE,USERDEFINED,NOTDEFINED}