package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcEvaporativeCoolerTypeEnum = ENUMERATION OF
 * (DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER
 * ,DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER
 * ,DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER
 * ,DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER
 * ,DIRECTEVAPORATIVEAIRWASHER
 * ,INDIRECTEVAPORATIVEPACKAGEAIRCOOLER
 * ,INDIRECTEVAPORATIVEWETCOIL
 * ,INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER
 * ,INDIRECTDIRECTCOMBINATION
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcevaporativecoolertypeenum.htm">IfcEvaporativeCoolerTypeEnum</a>
 */
public enum IfcEvaporativeCoolerTypeEnum {DIRECTEVAPORATIVERANDOMMEDIAAIRCOOLER,DIRECTEVAPORATIVERIGIDMEDIAAIRCOOLER,DIRECTEVAPORATIVESLINGERSPACKAGEDAIRCOOLER,DIRECTEVAPORATIVEPACKAGEDROTARYAIRCOOLER,DIRECTEVAPORATIVEAIRWASHER,INDIRECTEVAPORATIVEPACKAGEAIRCOOLER,INDIRECTEVAPORATIVEWETCOIL,INDIRECTEVAPORATIVECOOLINGTOWERORCOILCOOLER,INDIRECTDIRECTCOMBINATION,USERDEFINED,NOTDEFINED}