package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcHumidifierTypeEnum = ENUMERATION OF
 * (STEAMINJECTION
 * ,ADIABATICAIRWASHER
 * ,ADIABATICPAN
 * ,ADIABATICWETTEDELEMENT
 * ,ADIABATICATOMIZING
 * ,ADIABATICULTRASONIC
 * ,ADIABATICRIGIDMEDIA
 * ,ADIABATICCOMPRESSEDAIRNOZZLE
 * ,ASSISTEDELECTRIC
 * ,ASSISTEDNATURALGAS
 * ,ASSISTEDPROPANE
 * ,ASSISTEDBUTANE
 * ,ASSISTEDSTEAM
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifchumidifiertypeenum.htm">IfcHumidifierTypeEnum</a>
 */
public enum IfcHumidifierTypeEnum {STEAMINJECTION,ADIABATICAIRWASHER,ADIABATICPAN,ADIABATICWETTEDELEMENT,ADIABATICATOMIZING,ADIABATICULTRASONIC,ADIABATICRIGIDMEDIA,ADIABATICCOMPRESSEDAIRNOZZLE,ASSISTEDELECTRIC,ASSISTEDNATURALGAS,ASSISTEDPROPANE,ASSISTEDBUTANE,ASSISTEDSTEAM,USERDEFINED,NOTDEFINED}