package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcRoleEnum = ENUMERATION OF
 * (SUPPLIER
 * ,MANUFACTURER
 * ,CONTRACTOR
 * ,SUBCONTRACTOR
 * ,ARCHITECT
 * ,STRUCTURALENGINEER
 * ,COSTENGINEER
 * ,CLIENT
 * ,BUILDINGOWNER
 * ,BUILDINGOPERATOR
 * ,MECHANICALENGINEER
 * ,ELECTRICALENGINEER
 * ,PROJECTMANAGER
 * ,FACILITIESMANAGER
 * ,CIVILENGINEER
 * ,COMMISSIONINGENGINEER
 * ,ENGINEER
 * ,OWNER
 * ,CONSULTANT
 * ,CONSTRUCTIONMANAGER
 * ,FIELDCONSTRUCTIONMANAGER
 * ,RESELLER
 * ,USERDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcroleenum.htm">IfcRoleEnum</a>
 */
public enum IfcRoleEnum {SUPPLIER,MANUFACTURER,CONTRACTOR,SUBCONTRACTOR,ARCHITECT,STRUCTURALENGINEER,COSTENGINEER,CLIENT,BUILDINGOWNER,BUILDINGOPERATOR,MECHANICALENGINEER,ELECTRICALENGINEER,PROJECTMANAGER,FACILITIESMANAGER,CIVILENGINEER,COMMISSIONINGENGINEER,ENGINEER,OWNER,CONSULTANT,CONSTRUCTIONMANAGER,FIELDCONSTRUCTIONMANAGER,RESELLER,USERDEFINED}