package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcStairTypeEnum = ENUMERATION OF
 * (STRAIGHT_RUN_STAIR
 * ,TWO_STRAIGHT_RUN_STAIR
 * ,QUARTER_WINDING_STAIR
 * ,QUARTER_TURN_STAIR
 * ,HALF_WINDING_STAIR
 * ,HALF_TURN_STAIR
 * ,TWO_QUARTER_WINDING_STAIR
 * ,TWO_QUARTER_TURN_STAIR
 * ,THREE_QUARTER_WINDING_STAIR
 * ,THREE_QUARTER_TURN_STAIR
 * ,SPIRAL_STAIR
 * ,DOUBLE_RETURN_STAIR
 * ,CURVED_RUN_STAIR
 * ,TWO_CURVED_RUN_STAIR
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcstairtypeenum.htm">IfcStairTypeEnum</a>
 */
public enum IfcStairTypeEnum {STRAIGHT_RUN_STAIR,TWO_STRAIGHT_RUN_STAIR,QUARTER_WINDING_STAIR,QUARTER_TURN_STAIR,HALF_WINDING_STAIR,HALF_TURN_STAIR,TWO_QUARTER_WINDING_STAIR,TWO_QUARTER_TURN_STAIR,THREE_QUARTER_WINDING_STAIR,THREE_QUARTER_TURN_STAIR,SPIRAL_STAIR,DOUBLE_RETURN_STAIR,CURVED_RUN_STAIR,TWO_CURVED_RUN_STAIR,USERDEFINED,NOTDEFINED}