package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcSensorTypeEnum = ENUMERATION OF
 * (COSENSOR
 * ,CO2SENSOR
 * ,CONDUCTANCESENSOR
 * ,CONTACTSENSOR
 * ,FIRESENSOR
 * ,FLOWSENSOR
 * ,FROSTSENSOR
 * ,GASSENSOR
 * ,HEATSENSOR
 * ,HUMIDITYSENSOR
 * ,IDENTIFIERSENSOR
 * ,IONCONCENTRATIONSENSOR
 * ,LEVELSENSOR
 * ,LIGHTSENSOR
 * ,MOISTURESENSOR
 * ,MOVEMENTSENSOR
 * ,PHSENSOR
 * ,PRESSURESENSOR
 * ,RADIATIONSENSOR
 * ,RADIOACTIVITYSENSOR
 * ,SMOKESENSOR
 * ,SOUNDSENSOR
 * ,TEMPERATURESENSOR
 * ,WINDSENSOR
 * ,USERDEFINED
 * ,NOTDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcsensortypeenum.htm">IfcSensorTypeEnum</a>
 */
public enum IfcSensorTypeEnum {COSENSOR,CO2SENSOR,CONDUCTANCESENSOR,CONTACTSENSOR,FIRESENSOR,FLOWSENSOR,FROSTSENSOR,GASSENSOR,HEATSENSOR,HUMIDITYSENSOR,IDENTIFIERSENSOR,IONCONCENTRATIONSENSOR,LEVELSENSOR,LIGHTSENSOR,MOISTURESENSOR,MOVEMENTSENSOR,PHSENSOR,PRESSURESENSOR,RADIATIONSENSOR,RADIOACTIVITYSENSOR,SMOKESENSOR,SOUNDSENSOR,TEMPERATURESENSOR,WINDSENSOR,USERDEFINED,NOTDEFINED}