package com.howbuild.ifc.v4;

import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ArrayList;

/**
 * <pre>{@code
 * IfcUnitEnum = ENUMERATION OF
 * (ABSORBEDDOSEUNIT
 * ,AMOUNTOFSUBSTANCEUNIT
 * ,AREAUNIT
 * ,DOSEEQUIVALENTUNIT
 * ,ELECTRICCAPACITANCEUNIT
 * ,ELECTRICCHARGEUNIT
 * ,ELECTRICCONDUCTANCEUNIT
 * ,ELECTRICCURRENTUNIT
 * ,ELECTRICRESISTANCEUNIT
 * ,ELECTRICVOLTAGEUNIT
 * ,ENERGYUNIT
 * ,FORCEUNIT
 * ,FREQUENCYUNIT
 * ,ILLUMINANCEUNIT
 * ,INDUCTANCEUNIT
 * ,LENGTHUNIT
 * ,LUMINOUSFLUXUNIT
 * ,LUMINOUSINTENSITYUNIT
 * ,MAGNETICFLUXDENSITYUNIT
 * ,MAGNETICFLUXUNIT
 * ,MASSUNIT
 * ,PLANEANGLEUNIT
 * ,POWERUNIT
 * ,PRESSUREUNIT
 * ,RADIOACTIVITYUNIT
 * ,SOLIDANGLEUNIT
 * ,THERMODYNAMICTEMPERATUREUNIT
 * ,TIMEUNIT
 * ,VOLUMEUNIT
 * ,USERDEFINED);
 * }</pre>
 *
 * @see <a href="https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcunitenum.htm">IfcUnitEnum</a>
 */
public enum IfcUnitEnum {ABSORBEDDOSEUNIT,AMOUNTOFSUBSTANCEUNIT,AREAUNIT,DOSEEQUIVALENTUNIT,ELECTRICCAPACITANCEUNIT,ELECTRICCHARGEUNIT,ELECTRICCONDUCTANCEUNIT,ELECTRICCURRENTUNIT,ELECTRICRESISTANCEUNIT,ELECTRICVOLTAGEUNIT,ENERGYUNIT,FORCEUNIT,FREQUENCYUNIT,ILLUMINANCEUNIT,INDUCTANCEUNIT,LENGTHUNIT,LUMINOUSFLUXUNIT,LUMINOUSINTENSITYUNIT,MAGNETICFLUXDENSITYUNIT,MAGNETICFLUXUNIT,MASSUNIT,PLANEANGLEUNIT,POWERUNIT,PRESSUREUNIT,RADIOACTIVITYUNIT,SOLIDANGLEUNIT,THERMODYNAMICTEMPERATUREUNIT,TIMEUNIT,VOLUMEUNIT,USERDEFINED}